#!/bin/sh
#
# Hook script to verify what is about to be committed. Called by
# "git commit" with no arguments.  The hook should exit with
# non-zero status after issuing an appropriate message if it wants
# to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

cabal build

if [ $? != 0 ]
then
  echo "\nBroken library build. Fix and commit before pushing\n."
else
  echo "\nSuccessful FEECa build!\n"
fi

exit 0
